[package]
  distribution = "2201.3.1"
  export = ["greeting_service"]
  keywords = ["Kind/Sample","Type/RestApi","Category/Service","Internal/http"]
  name = "greeting_service"
  org = "bfsitest"
  version = "3.1.0"
